# Use this Blueprint to deploy n8n on Render as a web
# service that uses a Postgres database to store
# workflow data.

services:
  - type: web
    name: n8n-service
    plan: free
    runtime: image

    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      # n8n encryption key
      # Do not change after first deploy, or old credentials may become unreadable
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Database config
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"

      # n8n host / webhook config for Render
      - key: WEBHOOK_URL
        value: https://n8n-service-ijbl.onrender.com/
      - key: N8N_HOST
        value: https://n8n-service-ijbl.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: "443"
      - key: N8N_PROXY_HOPS
        value: "1"

      # Optional but recommended
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-service-ijbl.onrender.com/
      - key: N8N_SECURE_COOKIE
        value: "true"

      # Timezone
      - key: GENERIC_TIMEZONE
        value: Asia/Ho_Chi_Minh
      - key: TZ
        value: Asia/Ho_Chi_Minh

databases:
  - name: n8n-db
    plan: free
